### ISSUE TITLE
Upgrade to Ubuntu 24

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/reusable-workflows#16]
I noticed these annotations in a recent CI run:

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/1f11faeb-248f-425c-82be-16358dc6a77e" />

See https://github.com/actions/runner-images/issues/10636

**Comment by smol-ninja** [comment]
Our workflows don't specify any specific Ubuntu version. We use `ubuntu-latest` so it will automatically switch to 24.04 post Jan 17. I am closing this issue as there is no action required from our side.
